// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIcHcR8RBy6CJay9W6jiJiJWqUdbL7DI0',
    appId: '1:603966469908:web:99d98c0f0e1f86ae977401',
    messagingSenderId: '603966469908',
    projectId: 'ocake-flutter-app',
    authDomain: 'ocake-flutter-app.firebaseapp.com',
    storageBucket: 'ocake-flutter-app.firebasestorage.app',
    measurementId: 'G-RK9LKTYVBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAobH5f-8f5WH_APbom6OtRSFMdMNUcPdY',
    appId: '1:603966469908:android:64d8dba89c0859bc977401',
    messagingSenderId: '603966469908',
    projectId: 'ocake-flutter-app',
    storageBucket: 'ocake-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF6g5cVpY6UogZJ4qQ6YApHXtI35HVsgA',
    appId: '1:603966469908:ios:f82a8dceda1d48a5977401',
    messagingSenderId: '603966469908',
    projectId: 'ocake-flutter-app',
    storageBucket: 'ocake-flutter-app.firebasestorage.app',
    iosClientId: '603966469908-3mq9kgd43uanaf0548dgg0b3lkfad0ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.appOcake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF6g5cVpY6UogZJ4qQ6YApHXtI35HVsgA',
    appId: '1:603966469908:ios:f82a8dceda1d48a5977401',
    messagingSenderId: '603966469908',
    projectId: 'ocake-flutter-app',
    storageBucket: 'ocake-flutter-app.firebasestorage.app',
    iosClientId: '603966469908-3mq9kgd43uanaf0548dgg0b3lkfad0ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.appOcake',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIcHcR8RBy6CJay9W6jiJiJWqUdbL7DI0',
    appId: '1:603966469908:web:c1756a8c0771c94b977401',
    messagingSenderId: '603966469908',
    projectId: 'ocake-flutter-app',
    authDomain: 'ocake-flutter-app.firebaseapp.com',
    storageBucket: 'ocake-flutter-app.firebasestorage.app',
    measurementId: 'G-07E2XFX123',
  );
}
